.\" $Id: jerm.1,v 1.1 2004/05/15 10:15:16 mww Exp $
.\" Written by Kogule, Ryo
.\"
.Dd May 4, 2004
.Dt JERM 1
.Os
.Sh NAME
.Nm jerm
.Nd communication terminal through serial and TCP/IP interfaces
.Sh SYNOPSIS
.Nm
.Op Fl iz
.Op Fl l Ar log_file
.Op Fl b Ar speed
.Op Fl p Ar none|even|odd
.Op Fl d Ar 7|8
.Op Fl s Ar 1|1.5|2
.Op Fl f Ar none|x|hard
.Ar device_file
.Nm
.Op Fl 46
.Op Fl P Ar port
.Ar host_name
.Nm
.Fl D
.Op Fl 46
.Op Fl P Ar port
.Op Fl iz
.Op Fl l Ar log_file
.Ar device_file
.Sh DESCRIPTION
.Nm
is primarily intended to communicate with a remote machine through a
serial interface.  Additionally
.Nm
can communicate with another through a TCP/IP connection like
.Xr telnet 1
and relay a serial communication to a TCP/IP connection to another remote
machine.
.Pp
To connect a remote machine through a serial interface, use the first
form.  
.Ar device_file
should be a special device file of a serial interface (typically
.Pa /dev/cu* Ns ).\ \&
The second form lets
.Nm
connect to the remote machine
.Ar host_name
through the TCP port
.Ar port Ns .
In the case of invoking
.Nm
with the third form, it listens to the TCP port
.Ar port
first.  After a connection on the port is established, then
.Nm
opens the device
.Ar device_file
and relay the communications between the TCP port and the device.
See
.Sx EXAMPLES
for more information.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl i
Pipe mode.  Initialize the standard input/output as a serial interface.
.It Fl z
Empty the log file at first.
.It Fl l Ar log_file
Write output characters to
.Ar log_file Ns .
Since
.Nm
always appends characters to
.Ar log_file Ns ,
use
.Fl z
in conjunction with this flag to log a single session.
.It Fl b Ar speed
Designate the speed of serial interface. The default is 9600.
.It Fl p Ar n Ns Bo one Bc Ns |e Ns Bo ven Bc Ns |o Ns Bo dd Bc
Designate the parity of serial interface.  The valid value is one of
.Ql none Ns ,
.Ql even
or
.Ql odd Ns .
The first character is suffice.  The default is
.Ql none Ns .
.It Fl d Ar 7|8
Designate the bit length of data.  The default is
.Ql 8 Ns .
.It Fl s Ar 1|1.5|2
Designate the stop bit.  The default is
.Ql 1 Ns .
.It Fl f Ar n Ns Bo one Bc Ns |x|h Ns Bo ard Bc
Designate the flow control.  The default is
.Ql none Ns .
.It Fl 4
Use IPv4 for TCP/IP connection.
.It Fl 6
Use IPv6 for TCP/IP connection.
.It Fl P Ar port
Designate TCP port for TCP/IP connection. The default port is
.Ql 8086 Ns .
.El
.Ss Escape Characters
Typed characters are normally transmitted directly to the remote machine
(which does the echoing as well).  A tilde preceded by a Control-M or
Enter
.Pq Ql ^M\ \&~
is an escape signal; the following are recognized:
.Bl -tag -width flag
.It Ic ^M\ \&~\ \&.
Drop the connection and exit (you may still be logged in on the remote
machine).  When
.Nm
is invoked as a relaying server
.Pq with Fl D Ns
, Control-C
.Pq Ql ^C
will terminate
.Nm .
If in the pipe mode
.Po
.Fl i
is specified
.Pc Ns ,
.Nm
does not terminate.  Send a hang up signal
.Pq typically Ic kill -HUP
instead.
.It Ic ^M\ \&~\ \&~
Send a tilde
.Pq Ql \&~
to the remote machine.
.It Ic ^M\ \&~\ b
Send a
.Dv BREAK
to the remote machine.
.It Xo
.Ic ^M\ \&~\ >
.Pa file
.Xc
Send the local file
.Pa file
to the remote machine as its input.
.It Ic ^M\ \&~\ x
Toggle back and forth between the normal and the hexadecimal dump mode. The hexadecimal dump mode displays received characters in hexadecimal.
.It Ic ^M\ \&~\ ?
Get a summary of the
.Ql ^M \&~
escapes.
.El
.Sh EXAMPLES
The command:
.Dl jerm /dev/cuaa0 Pq Fx
.Dl jerm /dev/dty00 Pq Nx
.Dl jerm /dev/cua00 Pq Ox
.Dl jerm /dev/cu.usbmodemUSB-COM Pq Darwin/Mac OS X
connects a remote host through a serial interface.  The actual device file
may vary.
.Pp
When
.Fx HOST1
connects to the remote machine RMACH through a serial interface, The
command:
.Dl jerm -D -P 9800 -b 4800 /dev/cuaa0
on HOST1 will relay RMACH to TCP port 9800.  Then the command:
.Dl jerm -P 9800 HOST1
on
.Nx HOST2
can communicate with RMACH.  Instead of the above command, execute the
command:
.Dl jerm -i -P 9800 HOST1 -b 4800 < /dev/dty00 > /dev/dty00
on the HOST2 and connect HOST2's serial interface with Darwin HOST3, then
the command:
.Dl jerm /dev/cu.usbmodemUSB-COM
on HOST3 connects RMACH through HOST1 and HOST2.
.Sh SEE ALSO
.Xr cu 1 ,
.Xr tip 1 ,
.Xr telnet 1
.Sh AUTHOR
.An "KANDA Toshihiro"
.Sh BUGS
Although
.Nm
with TCP/IP connection is analogous to
.Xr telnet 1 ,
.Nm
does not support telnet protocol.
