--- guile.init.orig	2006-04-24 05:53:25.000000000 +0200
+++ guile.init	2006-11-08 21:09:43.000000000 +0100
@@ -58,7 +58,7 @@
 	  (and (defined? 'getenv) (getenv "SCHEME_LIBRARY_PATH"))
 	  ;; Use this path if your scheme does not support GETENV
 	  ;; or if SCHEME_LIBRARY_PATH is not set.
-	  "/usr/lib/slib/"
+	  "/opt/local/lib/slib/"
 	  (in-vicinity (implementation-vicinity) "slib/"))))
     (lambda () library-path)))
 
