--- RScheme.init.orig	2006-09-13 19:43:01.000000000 +0200
+++ RScheme.init	2006-11-08 21:06:40.000000000 +0100
@@ -48,7 +48,7 @@
 	  ;; Use this path if your scheme does not support GETENV
 	  ;; or if SCHEME_LIBRARY_PATH is not set.
 	  (case (software-type)
-	    ((unix) "/usr/lib/slib/")
+	    ((unix) "/opt/local/lib/slib/")
 	    ((vms) "lib$scheme:")
 	    ((ms-dos) "C:\\SLIB\\")
 	    (else "")))))
