--- guile.init.orig	2006-04-24 05:53:25.000000000 +0200
+++ guile.init	2006-11-09 21:56:00.000000000 +0100
@@ -324,7 +324,8 @@
     ;; tty).
     (define (browse-url url)
       (define (try cmd end) (zero? (system (string-append cmd url end))))
-      (or (try "netscape-remote -remote 'openURL(" ")'")
+      (or (try "open '" "'")
+	  (try "netscape-remote -remote 'openURL(" ")'")
 	  (try "netscape -remote 'openURL(" ")'")
 	  (try "netscape '" "'&")
 	  (try "netscape '" "'"))))
