/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@protocol UITextTraitsClient
+ (int)defaultAutoCapsType;	// IMP=0x324aabec
+ (int)defaultAutoCorrectionType;	// IMP=0x324aabf4
+ (BOOL)defaultAutoEnablesReturnKey;	// IMP=0x324aabfc
+ (struct CGColor *)defaultCaretColor;	// IMP=0x324aac14
+ (unsigned int)defaultCaretWidth;	// IMP=0x324aac58
+ (id)defaultEditingDelegate;	// IMP=0x324aac04
+ (int)defaultInitialSelectionBehavior;	// IMP=0x324aac0c
+ (int)defaultPreferredKeyboardType;	// IMP=0x324aac60
+ (int)defaultReturnKeyType;	// IMP=0x324aac68
+ (BOOL)defaultSecureTextEntryFlag;	// IMP=0x324aac70
+ (BOOL)defaultSingleCompletionEntryFlag;	// IMP=0x324aac78
+ (int)defaultTextDomain;	// IMP=0x324aac80
+ (int)defaultTextLoupeVisibility;	// IMP=0x324aac88
+ (id)defaultTextSuggestionDelegate;	// IMP=0x324aac90
+ (struct __CFCharacterSet *)defaultTextTrimmingSet;	// IMP=0x324aac98
+ (id)defaultTraits;	// IMP=0x324aaca0
- (int)autoCapsType;	// IMP=0x324ab3c4
- (int)autoCorrectionType;	// IMP=0x324ab3f8
- (BOOL)autoEnablesReturnKey;	// IMP=0x324ab42c
- (struct CGColor *)caretColor;	// IMP=0x324ab45c
- (unsigned int)caretWidth;	// IMP=0x324ab48c
- (void)dealloc;	// IMP=0x324aad44
- (id)editingDelegate;	// IMP=0x324ab43c
- (id)init;	// IMP=0x324aace8
- (int)initialSelectionBehavior;	// IMP=0x324ab44c
- (int)preferredKeyboardType;	// IMP=0x324ab49c
- (int)returnKeyType;	// IMP=0x324ab4ac
- (BOOL)secureTextEntry;	// IMP=0x324ab4bc
- (void)setAutoCapsType:(int)fp8;	// IMP=0x324ab3cc
- (void)setAutoCorrectionType:(int)fp8;	// IMP=0x324ab400
- (void)setAutoEnablesReturnKey:(BOOL)fp8;	// IMP=0x324ab434
- (void)setCaretColor:(struct CGColor *)fp8;	// IMP=0x324ab464
- (void)setCaretWidth:(unsigned int)fp8;	// IMP=0x324ab494
- (void)setEditingDelegate:(id)fp8;	// IMP=0x324ab444
- (void)setInitialSelectionBehavior:(int)fp8;	// IMP=0x324ab454
- (void)setPreferredKeyboardType:(int)fp8;	// IMP=0x324ab4a4
- (void)setReturnKeyType:(int)fp8;	// IMP=0x324ab4b4
- (void)setSecureTextEntry:(BOOL)fp8;	// IMP=0x324ab4c4
- (void)setSingleCompletionEntry:(BOOL)fp8;	// IMP=0x324ab4f4
- (void)setTextDomain:(int)fp8;	// IMP=0x324ab504
- (void)setTextLoupeVisibility:(int)fp8;	// IMP=0x324ab514
- (void)setTextSuggestionDelegate:(id)fp8;	// IMP=0x324ab524
- (void)setTextTrimmingSet:(struct __CFCharacterSet *)fp8;	// IMP=0x324ab534
- (void)setToDefaultValues;	// IMP=0x324ab0a0
- (void)setToSecureValues;	// IMP=0x324ab38c
- (BOOL)singleCompletionEntry;	// IMP=0x324ab4ec
- (void)takeTraitsFrom:(id)fp8;	// IMP=0x324aad98
- (int)textDomain;	// IMP=0x324ab4fc
- (int)textLoupeVisibility;	// IMP=0x324ab50c
- (id)textSuggestionDelegate;	// IMP=0x324ab51c
- (struct __CFCharacterSet *)textTrimmingSet;	// IMP=0x324ab52c

@end

