--- xpcom/components/nsIClassInfo.idl~	2004-04-18 16:18:13.000000000 +0200
+++ xpcom/components/nsIClassInfo.idl	2008-08-06 11:45:19.000000000 +0200
@@ -115,7 +115,7 @@
     // The high order bit is RESERVED for consumers of these flags. 
     // No implementor of this interface should ever return flags 
     // with this bit set.
-    const PRUint32 RESERVED             = 1 << 31;
+    const PRUint32 RESERVED             = 1U << 31;
 
 
     readonly attribute PRUint32 flags;
