--- vm-pop3d.init.org	2001-04-11 14:03:19.000000000 -0700
+++ vm-pop3d.init	2006-02-25 12:33:03.000000000 -0800
@@ -19,12 +19,13 @@
 	;;
   stop)
 	echo -n "Shutting down vm-pop3d: "
-	killproc vm-pop3d
+        pid=`ps axc|awk "{if (\\$5==\"vm-pop3d\") print \\$1}"`
+        /bin/kill $pid
 	echo
 	rm -f /var/lock/subsys/vm-pop3d
 	;;
   status)
-	status vm-pop3d
+	/bin/ps -ax |/usr/bin/grep vm-pop3d
 	;;
   restart)
 	$0 stop
