# See https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server
# for environment variables recognized by Ollama

export HOME=@@HOME@@
export OLLAMA_MODELS=@@MODELS_PATH@@
#export OLLAMA_CONTEXT_LENGTH=8192
#export OLLAMA_FLASH_ATTENTION=1
#export OLLAMA_KEEP_ALIVE=15m
#export OLLAMA_KV_CACHE_TYPE=q8_0
#export OLLAMA_NO_MMAP=1
