.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH REGED 8  "6th August 2014"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
reged \- utility to export/import and edit a Windows registry hives
.SH SYNOPSIS
.B reged
.RI [ options ]
.RI -x <registryhivefile> <prefixstring> <key> <output.reg>

.B reged
.RI [ options ]
.RI -I <registryhivefile> <prefixstring> <input.reg>

.B reged
.RI [ options ]
.RI -e  <registryhivefile>


.br
.SH DESCRIPTION
This manual page documents briefly the
.B reged
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.

.PP
.B reged
is the an interactive command line utility that can be used to
export, import or edit a Microsoft Windows registry hive.

.SH OPTIONS
.TP
.B \-h
Show summary of options.
.TP
.B \-x <registryhivefile> <prefixstring> <key> <output.reg>
Export parts of a hive file to a text registry (.reg)  file.
Prefixstring indicates the part of the registry hive to dump (for example
HKEY_LOCAL_MACHINE\\SOFTWARE). The <key> parameter defines the key to dump
(recursively). You can use \\ or \\\\ to list all the keys in the hive file.

Only one hive file and one .reg file can be defined.

.TP
.B \-I <registryhivefile> <prefixstring> <input.reg>
Import the content of the input.reg file into the registry file.  The value
<prefixstring> can be any valid prefix, for example is
HKEY_LOCAL_MACHINE\\SOFTWARE.

Only one .reg and one hive file supported at the same time

.TP
.B \-e <registryhive> ...
Interactive edit one or more registry files.

.TP
.B \-L
Log all changed filenames to /tmp/changed. When this option is set the
program automatically saves the changes in the hive files without prompting the
user.

Be careful when using the \fB-L\fR option as a root user in a multiuser system. 
The filename is fixed and this can be used by malicious users (dropping a
symlink with the same name) to overwrite system files.


.TP
.B \-C
Automatically save all changes. Do not prompt the user.

.TP
.B \-N
Do not allocate more information, only allow the editing of existing values with same size.

.TP
.B \-E
Do not expand the hive file (safe mode).

.TP
.B \-t
Print debug information of allocated blocks.

.TP
.B \-v
Print verbose information and debug messages.

.SH KNOWN BUGS

There are many \fBunknown\fR bugs. If you find bugs please report them to the author.

.SH SEE ALSO
.B chntpwd, samusrgrp, sampasswd
.br
You will find  more information available on how this program works, in the 
text files
.IR /usr/share/doc/chntpw/README.txt
and 
.IR /usr/share/doc/chntpw/MANUAL.txt

.SH AUTHOR
This program was written by Petter N Hagen.

This manual page was written by Javier Fernandez-Sanguino <jfs@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
