.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SAMPASSWD 8  "6th August 2014"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sampasswd \- reset passwords of users in the SAM user database
.SH SYNOPSIS
.B sampasswd
.RI [ options ]
.RI -u user
.RI < samfile > 
.br
.SH DESCRIPTION
This manual page documents briefly the
.B sampasswd
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.

.PP
.B sampasswd
is a non-interactive command line utility that can reset a user's
password and/or the user's account bits from the SAM user database file of a
Microsoft Windows system (Windows NT, 2000, XP, Vista, 7, 8.1, etc.).
This file is usually located at
\\WINDOWS\\system32\\config\\SAM on the file system of a Microsoft Windows 
Operating System

On success, the program does not output any informatin and the exit code is 0.

.SH OPTIONS
.TP
.B \-h
Show summary of options.
.TP
.B \-r
Reset the user's password.
.TP
.B \-a
Reset all the users. If this option is used there is no need to specify the next option.
.TP
.B \-u <user>
User to change. The user value can be provided as a username, or a RID number in
hexadecimal (if the username is preceded with '0x'). Usernames including
international characters will probably not work.
.TP
.B \-l
Lists the users in the SAM database.
.TP
.B \-H
Output human readable output. The program by default will print a parsable table unless
this option is used.
.TP
.B \-N
Do not allocate more information, only allow the editing of existing values with same size.
.TP
.B \-E
Do not expand the hive file (safe mode).
.TP
.B \-t
Print debug information of allocated blocks.
.TP
.B \-v
Print verbose information and debug messages.

.SH EXAMPLES
.TP
.B sampasswd -r -u theboss
Reset the password of a user named 'theboss', if found.

.TP
.B sampasswd -r -u 0x3ea
Reset the password of the user with RID '0x3a'.

.TP
.B samusrgrp -r -a
Reset the password of all the users in the Administrator's group (0x220)

.TP
.B samusrgrp -r -f
Reset the password of the administrative users with the lowest RID number.
This does not include the built-in administrator (0x1f4) unless no other
administrative user can be found in the database file.


.SH KNOWN BUGS

If the username includes international (non-ASCII) characters the program
will not (usually) find it. Use the RID number instead.

.SH SEE ALSO
.B chntpwd, reged, samusrgrp
.br
You will find  more information available on how this program works, in the
text files
.IR /usr/share/doc/chntpw/README.txt
and
.IR /usr/share/doc/chntpw/MANUAL.txt

More documentation is available at the upstream's author site:
.BR http://pogostick.net/~pnh/ntpasswd/

.SH AUTHOR
This program was written by Petter N Hagen.

This manual page was written by Javier Fernandez-Sanguino <jfs@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
