.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SAMUSRGRP 8  "6th August 2014"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
samusrgrp \- add or remove users from groups in SAM database files
.SH SYNOPSIS
.B samusrgrp
.RI [ options ]
.RI < samfile > 
.br
.SH DESCRIPTION
This manual page documents briefly the
.B samusrgrp
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
.B samusrgrp
is a non-interactive command line utility that can add or remove
a user from a local group that exists in the SAM user database of a
Microsoft Windows system (Windows NT, 2000, XP, Vista, 7, 8.1, etc.).
This file is usually located at
\\WINDOWS\\system32\\config\\SAM on the file system of a Microsoft Windows
Operating System

On success, the program does not output any informatin and the exit code is 0.

The binary program supports multiple names. If it is called named
.B samusrtogrp
it will assume \fB-a\fR mode (add user). If it is called named
.B samusrfromgrp
it will assume \fB-r\fR mode (remove user).

.SH OPTIONS
.TP
.B \-h
Show summary of options.
.TP
.B \-a
The user is added to the group.  This option has to be followed
by \-u and \-g .
.TP
.B \-r
The user is removed from the group.  This option has to be followed
by \-u and \-g .
.TP
.B \-u <user>
User to change. The user value can be provided as a username, or a RID number in
hexadecimal (if the username is preceded with '0x'). Usernames including
international characters will probably not work.
.TP
.B \-g <group>
Group to change. The group can only be given as a group number, in hexadecimal, preceded with 
with '0x'.
.TP
.B \-l
Lists the groups in the SAM database.
.TP
.B \-L
Lists the groups in the SAM database as well as their members.
.TP
.B \-s
Print the machine SID.
.TP
.B \-H
Output human readable output. The program by default will print a parsable table unless
this option is used.
.TP
.B \-N
Do not allocate more information, only allow the editing of existing values
with same size.
.TP
.B \-E
Do not expand the hive file (safe mode).
.TP
.B \-t
Print debug information of allocated blocks.
.TP
.B \-v
Print verbose information and debug messages.

.SH EXAMPLES
.TP
.B samusrgrp -a -u theboss -g 0x220 SAMFILE
Adds a user named 'theboss' to the group 0x220 (Administrators)

.TP
.B samusrgrp -a -u 0x3ea -g 0x221 SAMFILE
Adds a user with the id '0x3aa' to the group 0x221 (Users)

.TP
.B samusrgrp -r -u 0x3ff -g 0x221 SAMFILE
Remove a user with the id '0x3ff' from the group 0x221 (Users)

.SH KNOWN BUGS

If the username includes international (non-ASCII) characters the program
will not (usually) find it. Use the RID number instead.

.SH SEE ALSO
.B chntpwd, reged, sampasswd
.br
You will find  more information available on how this program works, in the 
text files
.IR /usr/share/doc/chntpw/README.txt
and 
.IR /usr/share/doc/chntpw/MANUAL.txt

More documentation is available at the upstream's author site:
.BR http://pogostick.net/~pnh/ntpasswd/

.SH AUTHOR
This program was written by Petter N Hagen.

This manual page was written by Javier Fernandez-Sanguino <jfs@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
