[build-system]
requires = ["flit_core >=4"]
build-backend = "flit_core.buildapi"

[project]
name = "socksio"
dynamic = ["version", "description"]
readme = "README.md"
requires-python = ">=3.6"
license = {text = "MIT"}
authors = [
    {name = "Seth Michael Larson", email = "sethmichaellarson@gmail.com"},
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Internet :: Proxy Servers",
]

[project.urls]
Home = "https://github.com/sethmlarson/socksio"
