--- test/SLPDereg/test.script.orig	Sun Dec  3 23:58:17 2000
+++ test/SLPDereg/test.script	Thu May  6 20:42:56 2004
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+PIDDIR=@@PREFIX@@/var/run
 echo "SLPDereg"
 rm -f SLPDereg.actual.output
 scriptdir=${srcdir}/SLPDereg
@@ -10,5 +11,5 @@
 ./slpdereg service:registered 10.0.0.1 service:unregistered 10.0.0.1 >> SLPDereg.actual.output
 echo >> SLPDereg.actual.output
 ./slpdereg service:test 10.0.0.1 >> SLPDereg.actual.output
-if test -f /var/run/slpd.pid; then kill `cat /var/run/slpd.pid`; fi
+if test -f ${PIDDIR}/slpd.pid; then kill `cat ${PIDDIR}/slpd.pid`; fi
 diff -c ${scriptdir}/SLPDereg.expected.output SLPDereg.actual.output
