--- test/SLPFindSrvs/test.script.orig	Sun Dec  3 23:59:02 2000
+++ test/SLPFindSrvs/test.script	Thu May  6 20:48:40 2004
@@ -1,10 +1,11 @@
 #!/bin/sh
 
+PIDDIR=@@PREFIX@@/var/run
 echo "SLPFindSrvs"
 rm -f SLPFindSrvs.actual.output
 scriptdir=${srcdir}/SLPFindSrvs
 
 ../slpd/slpd -r ${scriptdir}/slp.test.reg 
 ./slpfindsrvs service:test >> SLPFindSrvs.actual.output
-if test -f /var/run/slpd.pid; then kill `cat /var/run/slpd.pid`; fi
+if test -f ${PIDDIR}/slpd.pid; then kill `cat ${PIDDIR}/slpd.pid`; fi
 diff -c ${scriptdir}/SLPFindSrvs.expected.output SLPFindSrvs.actual.output
