--- test/SLPOpen/test.script.orig	Sun Dec  3 23:59:02 2000
+++ test/SLPOpen/test.script	Thu May  6 20:49:54 2004
@@ -1,10 +1,11 @@
 #!/bin/sh 
 
+PIDDIR=@@PREFIX@@/var/run
 echo "SLPOpen"
 rm -f SLPOpen.actual.output
 scriptdir=${srcdir}/SLPOpen
 
 ../slpd/slpd -r ${scriptdir}/slp.test.reg 
 ./slpopen > SLPOpen.actual.output
-if test -f /var/run/slpd.pid; then kill `cat /var/run/slpd.pid`; fi
+if test -f ${PIDDIR}/slpd.pid; then kill `cat ${PIDDIR}/slpd.pid`; fi
 diff -c ${scriptdir}/SLPOpen.expected.output SLPOpen.actual.output
