--- test/SLPFindAttrs/test.script.orig	Sun Dec  3 23:58:17 2000
+++ test/SLPFindAttrs/test.script	Thu May  6 20:45:47 2004
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+PIDDIR=@@PREFIX@@/var/run
 echo "SLPFindAttrs"
 rm -f SLPFindAttrs.actual.output 
 scriptdir=${srcdir}/SLPFindAttrs
@@ -15,5 +16,5 @@
 echo >> SLPFindAttrs.actual.output
 ./slpfindattrs service:test 10.0.0.1 "(foo=value1,value2)" goo >> SLPFindAttrs.actual.output
 echo >> SLPFindAttrs.actual.output
-if test -f /var/run/slpd.pid; then kill `cat /var/run/slpd.pid`; fi
+if test -f ${PIDDIR}/slpd.pid; then kill `cat ${PIDDIR}/slpd.pid`; fi
 diff -c ${scriptdir}/SLPFindAttrs.expected.output SLPFindAttrs.actual.output
