--- test/SLPReg/test.script.orig	Sun Dec  3 23:59:02 2000
+++ test/SLPReg/test.script	Thu May  6 20:51:07 2004
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+PIDDIR=@@PREFIX@@/var/run
 echo "SLPReg"
 rm -f SLPReg.actual.output
 scriptdir=${srcdir}/SLPReg
@@ -8,5 +9,5 @@
 ./slpreg service:valid 10.0.0.1 service:valid >>  SLPReg.actual.output
 echo >> SLPReg.actual.output
 ./slpreg service:valid 10.0.0.1 service:invalid >> SLPReg.actual.output
-if test -f /var/run/slpd.pid; then kill `cat /var/run/slpd.pid`; fi
+if test -f ${PIDDIR}/slpd.pid; then kill `cat ${PIDDIR}/slpd.pid`; fi
 diff -c ${scriptdir}/SLPReg.expected.output SLPReg.actual.output
