--- test/SLPFindSrvTypes/test.script.orig	Sun Dec  3 23:58:17 2000
+++ test/SLPFindSrvTypes/test.script	Thu May  6 20:47:18 2004
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+PIDDIR=@@PREFIX@@/var/run
 echo "SLPFindSrvTypes"
 rm -f SLPFindSrvTypes.actual.output
 scriptdir=${srcdir}/SLPFindSrvTypes
@@ -13,5 +14,5 @@
 echo >> SLPFindSrvTypes.actual.output
 ./slpfindsrvtypes "OPENSLP" >> SLPFindSrvTypes.actual.output
 
-if test -f /var/run/slpd.pid; then kill `cat /var/run/slpd.pid`; fi
+if test -f ${PIDDIR}/slpd.pid; then kill `cat ${PIDDIR}/slpd.pid`; fi
 diff -c ${scriptdir}/SLPFindSrvTypes.expected.output SLPFindSrvTypes.actual.output
