#!/usr/bin/env python3
"""
mupdf_ocr_extract.py
=====================

Text-extraction test tool built directly on the raw `mupdf` Python module
(the one generated by ArtifexSoftware/mupdf's scripts/mupdfwrap.py, i.e.
`import mupdf` -> mupdf.py + _mupdf.so -- NOT the higher-level `fitz` /
PyMuPDF wrapper).

Strategy per page:
  1. Try normal ("native") text extraction via a structured text page
     (mupdf.StextPage). This is fast and exact for text-based PDFs.
  2. If the page yields little or no text (or --force-ocr is given),
     fall back to OCR: rasterize the page to a Pixmap, hand it to
     MuPDF's built-in Tesseract-based OCR writer
     (fz_save_pixmap_as_pdfocr), which produces a tiny 1-page "OCR PDF"
     with an invisible text layer. We reopen that 1-page PDF and pull
     the text back out using the same StextPage path.

This mirrors what MuPDF's own OCR support does internally (mutool's
integrated Tesseract OCR) -- there's no separate pytesseract/tesseract
CLI dependency; Tesseract is compiled into libmupdfcpp itself. You do,
however, need Tesseract *language data files* ("tessdata") available,
either via $TESSDATA_PREFIX or --tessdata.

Because the exact attribute names on generated wrapper classes
(mupdf.PdfocrOptions, mupdf.StextOptions, etc.) can shift slightly
between MuPDF releases, run this script once with --introspect first
to confirm what your particular build actually exposes:

    python3 mupdf_ocr_extract.py --introspect

Usage
-----
    python3 mupdf_ocr_extract.py input.pdf -o out_dir
    python3 mupdf_ocr_extract.py input.pdf -o out_dir --force-ocr --lang eng
    python3 mupdf_ocr_extract.py input.pdf -o out_dir --tessdata /opt/local/share/tessdata
"""

import argparse
import json
import os
import sys
import tempfile
import textwrap


def die(msg, code=1):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(code)


def introspect(mupdf):
    """Print what this build's bindings actually expose, for diagnosing
    API-name drift between MuPDF versions -- and, more fundamentally,
    whether `import mupdf` is even resolving to the real module at all."""
    print(f"mupdf.__file__: {getattr(mupdf, '__file__', '<none>')}")
    print(f"mupdf.__path__: {list(getattr(mupdf, '__path__', []))}")
    is_namespace_pkg = getattr(mupdf, "__file__", None) is None
    print(f"looks like an empty namespace package: {is_namespace_pkg}")
    print()

    if is_namespace_pkg:
        print("!! `import mupdf` did NOT load your real mupdf.py/_mupdf.so.")
        print("   Something earlier on sys.path is an empty directory named")
        print("   'mupdf' (no __init__.py), which Python treats as a stub")
        print("   namespace package and stops looking further. Likely causes:")
        print("     - running this script from a directory that itself")
        print("       contains a subfolder literally named 'mupdf'")
        print("       (python inserts the script's own directory at the")
        print("       front of sys.path when run as `python3 script.py`)")
        print("     - a stray/partial 'mupdf' dir earlier in PYTHONPATH")
        print()
        print("sys.path (in search order):")
        for p in sys.path:
            marker = ""
            try:
                if p and os.path.isdir(os.path.join(p, "mupdf")):
                    marker = "  <-- has an 'mupdf' subdirectory here"
                elif p and os.path.isfile(os.path.join(p, "mupdf.py")):
                    marker = "  <-- real mupdf.py lives here"
            except OSError:
                pass
            print(f"  {p!r}{marker}")
        print()
        print("Try: cd somewhere with no 'mupdf' subfolder and rerun, or")
        print("     python3 -c \"import mupdf; print(mupdf.__file__)\"")
        print("     to confirm resolution outside this script's directory.")
        return

    version_fn = getattr(mupdf, "FZ_VERSION", None) or getattr(mupdf, "fz_version", None)
    print(f"FZ_VERSION attr:   {version_fn!r}")
    print()

    def show(prefix):
        names = sorted(n for n in dir(mupdf) if prefix.lower() in n.lower())
        print(f"-- names containing {prefix!r} ({len(names)}) --")
        for n in names:
            print(f"   {n}")
        print()

    for prefix in ("Stext", "Pdfocr", "pdfocr", "Ocr", "Pixmap", "save_pixmap",
                   "new_pixmap_from_page", "Document", "scale", "TextPage"):
        show(prefix)


def open_document(mupdf, path):
    """Return (doc, count_pages_fn, load_page_fn) using whichever document
    API this particular mupdf build actually exposes. Different builds of
    the raw `mupdf` module have used different naming schemes over time:
      - current PyPI-style:      mupdf.Document(path), doc.count_pages(), doc.load_page(i)
      - older 'Fz'-prefixed:     mupdf.FzDocument(path), doc.fz_count_pages(), doc.fz_load_page(i)
      - class-wrapper-less:      mupdf.fz_open_document(path) + free functions
    """
    if hasattr(mupdf, "Document"):
        doc = mupdf.Document(path)
        return doc, doc.count_pages, doc.load_page

    if hasattr(mupdf, "FzDocument"):
        doc = mupdf.FzDocument(path)
        count = getattr(doc, "fz_count_pages", None) or getattr(doc, "count_pages", None)
        load = getattr(doc, "fz_load_page", None) or getattr(doc, "load_page", None)
        if count and load:
            return doc, count, load

    if hasattr(mupdf, "fz_open_document"):
        doc = mupdf.fz_open_document(path)
        return doc, (lambda: mupdf.fz_count_pages(doc)), (lambda i: mupdf.fz_load_page(doc, i))

    raise AttributeError(
        "could not find any way to open a document in this mupdf build "
        "(checked Document, FzDocument, fz_open_document). Run with "
        "--introspect and look for anything containing 'document' "
        "(case-insensitive) in the output, then adjust open_document()."
    )


def resolve(mupdf, *names):
    """Return the first attribute of `mupdf` that exists, from a list of
    candidate names -- lets us cope with naming drift between builds
    (e.g. 'StextOptions' vs the older 'FzStextOptions')."""
    for n in names:
        if hasattr(mupdf, n):
            return getattr(mupdf, n)
    raise AttributeError(f"none of {names!r} found in this mupdf build "
                          f"(run --introspect to see what IS available)")


def get_stext_text(mupdf, page):
    """Extract plain text from a page's structured text, in reading order,
    using the documented block/line/char walk."""
    StextOptions = resolve(mupdf, "StextOptions", "FzStextOptions")
    StextPage = resolve(mupdf, "StextPage", "FzStextPage")
    stext_options = StextOptions()
    stextpage = StextPage(page, stext_options)

    out = []
    for block in stextpage:
        block_ = block.m_internal
        if int(block_.type) != 0:  # 0 == FZ_STEXT_BLOCK_TEXT
            continue
        for line in block:
            chars = []
            for ch in line:
                chars.append(chr(ch.m_internal.c))
            out.append("".join(chars))
    return "\n".join(out)


def ocr_page_text(mupdf, page, dpi, lang, tessdata, workdir):
    """Rasterize `page` and run it through MuPDF's built-in Tesseract OCR
    writer, then read the text back out of the resulting 1-page PDF."""
    zoom = dpi / 72.0
    ctm = mupdf.fz_scale(zoom, zoom)
    colorspace = mupdf.fz_device_rgb()
    pixmap = mupdf.fz_new_pixmap_from_page(page, ctm, colorspace, 0)

    PdfocrOptions = resolve(mupdf, "PdfocrOptions", "FzPdfocrOptions")
    opts = PdfocrOptions()
    # .compress is confirmed present across versions; language/tessdata
    # are set defensively in case a given build spells them differently.
    try:
        opts.compress = 1
    except AttributeError:
        pass
    if lang:
        for attr in ("language", "ocr_language", "lang"):
            if hasattr(opts, attr):
                setattr(opts, attr, lang)
                break
    if tessdata:
        for attr in ("tessdata", "datadir", "ocr_tessdata"):
            if hasattr(opts, attr):
                setattr(opts, attr, tessdata)
                break

    tmp_pdf = os.path.join(workdir, "ocr_page.pdf")
    if os.path.exists(tmp_pdf):
        os.remove(tmp_pdf)

    # append=0 -> create a fresh single-page PDF.
    mupdf.fz_save_pixmap_as_pdfocr(pixmap, tmp_pdf, 0, opts)

    ocr_doc, _, ocr_load_page = open_document(mupdf, tmp_pdf)
    ocr_page = ocr_load_page(0)
    text = get_stext_text(mupdf, ocr_page)
    try:
        os.remove(tmp_pdf)
    except OSError:
        pass
    return text


def parse_page_range(spec, page_count):
    if not spec:
        return list(range(page_count))
    pages = set()
    for part in spec.split(","):
        part = part.strip()
        if "-" in part:
            a, b = part.split("-", 1)
            a = int(a) if a else 1
            b = int(b) if b else page_count
            pages.update(range(a - 1, b))
        else:
            pages.add(int(part) - 1)
    return sorted(p for p in pages if 0 <= p < page_count)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("pdf", nargs="?", help="input PDF file")
    ap.add_argument("-o", "--outdir", default="ocr_out",
                     help="directory to write extracted text/manifest into (default: ocr_out)")
    ap.add_argument("--pages", help="page range, e.g. '1-3,7' (1-based, default: all)")
    ap.add_argument("--lang", default="eng",
                     help="Tesseract language code(s), e.g. 'eng' or 'eng+fra' (default: eng)")
    ap.add_argument("--tessdata", default=os.environ.get("TESSDATA_PREFIX"),
                     help="path to Tesseract tessdata dir (default: $TESSDATA_PREFIX)")
    ap.add_argument("--dpi", type=int, default=300, help="OCR rasterization DPI (default: 300)")
    ap.add_argument("--min-chars", type=int, default=20,
                     help="native-text char threshold below which OCR is triggered (default: 20)")
    ap.add_argument("--force-ocr", action="store_true",
                     help="always OCR every page, ignore native text")
    ap.add_argument("--introspect", action="store_true",
                     help="print what this build's mupdf module exposes, then exit")
    args = ap.parse_args()

    try:
        import mupdf
    except ImportError as e:
        die(f"could not import the 'mupdf' module ({e}); "
            f"is it on PYTHONPATH / installed in this interpreter's site-packages?")

    if args.introspect:
        introspect(mupdf)
        return

    if not args.pdf:
        ap.error("a PDF file is required unless using --introspect")
    if not os.path.exists(args.pdf):
        die(f"input file not found: {args.pdf}")

    os.makedirs(args.outdir, exist_ok=True)

    doc, count_pages, load_page = open_document(mupdf, args.pdf)
    page_count = count_pages()
    page_indices = parse_page_range(args.pages, page_count)

    manifest = {"input": os.path.abspath(args.pdf), "pages": []}
    combined = []

    with tempfile.TemporaryDirectory(prefix="mupdf_ocr_") as workdir:
        for i in page_indices:
            page = load_page(i)
            method = "native"
            text = ""
            if not args.force_ocr:
                try:
                    text = get_stext_text(mupdf, page)
                except Exception as e:
                    print(f"warning: native extraction failed on page {i + 1}: {e}",
                          file=sys.stderr)

            if args.force_ocr or len(text.strip()) < args.min_chars:
                try:
                    text = ocr_page_text(
                        mupdf, page, args.dpi, args.lang, args.tessdata, workdir
                    )
                    method = "ocr"
                except Exception as e:
                    print(f"warning: OCR failed on page {i + 1}: {e}", file=sys.stderr)
                    method = "failed"

            page_path = os.path.join(args.outdir, f"page_{i + 1:04d}.txt")
            with open(page_path, "w", encoding="utf-8") as f:
                f.write(text)

            manifest["pages"].append(
                {"page": i + 1, "method": method, "chars": len(text), "file": page_path}
            )
            combined.append(f"----- page {i + 1} ({method}) -----\n{text}")
            print(f"page {i + 1:>4}/{page_count}: {method:6s} {len(text):6d} chars")

    combined_path = os.path.join(args.outdir, "combined.txt")
    with open(combined_path, "w", encoding="utf-8") as f:
        f.write("\n\n".join(combined))

    manifest_path = os.path.join(args.outdir, "manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    print()
    print(textwrap.dedent(f"""\
        done.
          combined text : {combined_path}
          manifest      : {manifest_path}
          per-page files: {args.outdir}/page_NNNN.txt
        """))


if __name__ == "__main__":
    main()
