--- CMake/InstallResources.cmake.orig	2011-05-08 20:28:04.000000000 +0200
+++ CMake/InstallResources.cmake	2011-11-11 04:44:58.000000000 +0100
@@ -20,7 +20,7 @@
   set(OGRE_SAMPLES_DIR_REL ".")
   set(OGRE_SAMPLES_DIR_DBG ".")
   set(OGRE_CFG_INSTALL_PATH "bin")
-elseif (APPLE)
+elseif (APPLE AND NOT MACPORTS)
   set(OGRE_MEDIA_PATH "Media")
   if(OGRE_BUILD_PLATFORM_IPHONE)
     set(OGRE_MEDIA_DIR_REL "${OGRE_MEDIA_PATH}")
@@ -42,7 +42,7 @@
   set(OGRE_SAMPLES_DIR_REL "")
   set(OGRE_SAMPLES_DIR_DBG "")
   set(OGRE_CFG_INSTALL_PATH "bin")
-elseif (UNIX)
+elseif (UNIX OR MACPORTS)
   set(OGRE_MEDIA_PATH "share/OGRE/media")
   set(OGRE_MEDIA_DIR_REL "${CMAKE_INSTALL_PREFIX}/${OGRE_MEDIA_PATH}")
   set(OGRE_MEDIA_DIR_DBG "${CMAKE_INSTALL_PREFIX}/${OGRE_MEDIA_PATH}")
