# Defaults that may still need to be set
prefix              	/opt/local
portdbpath          	/opt/local/var/macports
applications_dir    	/Applications/MacPorts
frameworks_dir      	/opt/local/Library/Frameworks
sources_conf        	/opt/local/etc/macports/sources.conf
archive_sites_conf      /opt/local/etc/macports/archive_sites.conf
pubkeys_conf            /opt/local/etc/macports/pubkeys.conf
variants_conf       	/opt/local/etc/macports/variants.conf

# CI is not interactive
ui_interactive no

# Only download from the CDN, not the mirrors
host_blacklist *.distfiles.macports.org *.packages.macports.org
# Prefer hosts close to github
preferred_hosts mirror.fcix.net github.com *.github.com
# Also try downloading archives from the private server
archive_site_local https://packages-private.macports.org/:tbz2
