/* Generated by autorevision - do not hand-hack! */
#ifndef AUTOREVISION_H
#define AUTOREVISION_H

#define VCS_TYPE		"git"
#define VCS_BASENAME	"wesnoth-1.14.13"
#define VCS_UUID		"4430149d4638748d8925de01e26b5a74b59d1cb6"
#define VCS_NUM			1
#define VCS_DATE		"2020-06-13T04:10:29Z"
#define VCS_BRANCH		""
#define VCS_TAG			"1.14.13"
#define VCS_TICK		0
#define VCS_EXTRA		""

#define VCS_ACTION_STAMP	"2020-06-13T04:10:29Z!shadowm@wesnoth.org"
#define VCS_FULL_HASH		"4430149d4638748d8925de01e26b5a74b59d1cb6"
#define VCS_SHORT_HASH		"4430149d"

#define VCS_WC_MODIFIED		1

#endif

/* end */
