/* Generated by autorevision - do not hand-hack! */
#ifndef AUTOREVISION_H
#define AUTOREVISION_H

#define VCS_TYPE		"git"
#define VCS_BASENAME	"wesnoth-1.14.17"
#define VCS_UUID		"8d6c8ef78de0e4b78ef1a929b80eafae99d2d9aa"
#define VCS_NUM			1
#define VCS_DATE		"2021-06-20T18:12:56Z"
#define VCS_BRANCH		""
#define VCS_TAG			"1.14.17"
#define VCS_TICK		0
#define VCS_EXTRA		""

#define VCS_ACTION_STAMP	"2021-06-20T18:12:56Z!pentarctagon@tutamail.com"
#define VCS_FULL_HASH		"8d6c8ef78de0e4b78ef1a929b80eafae99d2d9aa"
#define VCS_SHORT_HASH		"8d6c8ef7"

#define VCS_WC_MODIFIED		0

#endif

/* end */
